angular.module("homeSite").controller("homeCtrl", function ($scope, bannerAPI, $http) {
    // Generic home page of website messages:
    $scope.welcome_message = "Seja bem vindo à Imobiliária Florença";
    $scope.como_alugar_message = "Ao locador a documentação necessária é a certidão atualizada do imóvel, comprovante de endereço, CPF e documento de identidade.";
    $scope.como_vender_message = "Se você deseja vender ou comprar um imóvel, assessoramos você neste processo, desde o momento da assinatura da autorização até a conclusão da venda.";
    $scope.beneficios_message = "Ao locatário oferecemos a possibilidade de apresentar como garantia de fiança, as seguintes opções: Um fiador com um imóvel, seguro fiança ou Título de Capitalização, o que viabiliza a locação pretendida.";
    $scope.facilidades_message = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.";
    $scope.ligue_para_nos_message = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.";

    // Specific lists of home page:

    $scope.parameters = []

    var loadParameters = function () {
        // $http.get("http://localhost:3412/contatos").success(function (data) {
        bannerAPI.getBanners().success(function (data) {
            $scope.parameters = data;
        }).error(function (data, status) {
            console.log("Aconteceu um problema no backend: " + data)
            $scope.message = "Aconteceu um problema no backend: " + data;
        });
    };


    $scope.active_banners = [];

    var loadBanners = function () {
        // $http.get("http://localhost:3412/contatos").success(function (data) {
        bannerAPI.getBanners().success(function (data) {
            $scope.active_banners = data;
        }).error(function (data, status) {
            console.log("Aconteceu um problema no backend: " + data)
            $scope.message = "Aconteceu um problema no backend: " + data;
        });
    };

    $scope.imoveis_in_destaq = [];

    var loadDestaques = function () {
        $http.get("http://localhost:3412/contatos").success(function (data) {
            $scope.imoveis_in_destaq = data;
        }).error(function (data, status) {
            console.log("Aconteceu um problema no backend: " + data)
            $scope.message = "Aconteceu um problema no backend: " + data;
        });

    };

    $scope.active_banners = [
        {src: "img/foto_08_1900x1080.jpg", caption: "Experiência no mercado imobiliário."},
        {src: "img/foto_02_1900x1080.jpg", caption: "Departamento jurídico próprio."},
        {src: "img/foto_07_1900x1080.jpg", caption: "Atendimento personalizado."}
    ];
    $scope.imoveis_in_destaq = [
        {href: "#", code: "A 04.02", title: "<p>Apartamento com 1 dormit&oacute;rio, sala, cozinha, &aacute;rea de servi&ccedil;o, banheiro e Box para carro.</p>", src: "https://lh6.googleusercontent.com/-LmZEYBVNVwE/UPb-qMavopI/AAAAAAAADNQ/v6hSQukTLvg/s576/DSC05073.JPG"},
        {href: "#", code: "L 02.01", title: "<p>Sal&atilde;o grande com banheiro.</p>", src: "https://lh4.googleusercontent.com/-P6zH-jR1yDU/Ty84bsy66NI/AAAAAAAABzk/B2xIZTXJOtw/s576/DSC02211.JPG"},
        {href: "#", code: "J 13.09", title: "<p>Duas lojas Comercias, medido aproximadamente 70 m&sup2;&nbsp;</p>", src: "https://lh5.googleusercontent.com/-5PfutR-HzEg/VIskPveNyJI/AAAAAAAAH90/ZIPWfJlj1R8/w576-h300-no/DSC09829.JPG"},
        {href: "#", code: "F 01.01", title: "<p>Apartamento com 2 dormit&oacute;rios, banheiro, sala, cozinha ampla, sala de jantar, &aacute;rea de servi&ccedil;o e sacada.</p>", src: "https://lh6.googleusercontent.com/-URRhVCdbVxI/TpSIGDplcYI/AAAAAAAAA8Q/PiR3EKcp8ko/s576/Site.JPG"},
        {href: "#", code: "G 01.02", title: "<p>Sala n&deg;. 703 Fundos, com 41,86 m&sup2; e um banheiro.</p>", src: "https://lh6.googleusercontent.com/-aejR4kawSFY/UP7kNvUtG9I/AAAAAAAADVs/vk_ZUf_GxbA/s576/DSC02508.JPG"},
        {href: "#", code: "S 04.01", title: "<p>Apartamento com &aacute;rea total de 119.715 m&sup2;, e &aacute;rea privativa de 97.794 m&sup2;, localizado no 3&ordm; pavimento, com elevador. Possui 2 dormit&oacute;rios, sala ampla, cozinha, 2 banheiros, &aacute;rea de servi&ccedil;o, depend&ecirc;ncia de empregada, sacada e Box coberto na garagem com 24.360 m&sup2;.</p>", src: "https://lh6.googleusercontent.com/-k9MpPAlHNTs/UOsN8WoJHkI/AAAAAAAADFw/CLJSaDmz7Tc/s576/DSC03494.JPG"},
        {href: "#", code: "L 05.01", title: "<p>SALA COMERCIAL com 30 m&sup2; e um Banheiro</p>", src: "https://lh5.googleusercontent.com/-5hrroRGSUgg/Ticn4kzz6KI/AAAAAAAAAWg/5hOHkJ8EGl0/DSC00090.JPG"},
        {href: "#", code: "GI004", title: "<p>Pavilh&atilde;o novo&nbsp;com 1080 m&sup2;, 6 metros de p&eacute; direito, piso polido, 144m&sup2; de escrit&oacute;rios, constru&iacute;do em uma &aacute;rea de 30.000 m&sup2; com viabilidade para ind&uacute;stria, frente asfaltada, &agrave; 1500 metros da RS 118 em Gravata&iacute;/RS. ESTUDAMOS A &nbsp;PROPOSTA.</p>", src: "https://lh3.googleusercontent.com/-5s2xPJjvH6c/UfpcJsWGnpI/AAAAAAAAEWs/43tMFMEa_Cs/s640/DSC05943.JPG"},
        {href: "#", code: "J 02.00", title: "<p>Apartamento n&deg;.201, &nbsp;Fundos com 2 dormit&oacute;rios, sala, cozinha, &aacute;rea de servi&ccedil;o, banheiro <span style=''font-family: Arial, Helvetica, sans-serif; font-size: 13px; line-height: 28px;>e garagem coberta.</span></p><p>&nbsp;</p>", src: "https://lh6.googleusercontent.com/-D6-SY5WnnGI/US-uGlY892I/AAAAAAAADi8/IpNBNB7Emj0/s576/DSC05613.JPG"},
        {href: "#", code: "M 01.01", title: "<p>Apartamento &Aacute;rea privativa: 2 Dormit&oacute;rios, 1 Banheiro, Sala, Cozinha, &Aacute;rea de servi&ccedil;o e Garagem para 1 carro coberta. &Aacute;rea social: P&aacute;tio com Brinquedos, Portaria 24h, Sal&atilde;o de festas e Quadra de Esportes.</p>", src: "https://lh5.googleusercontent.com/-MDNn3KfvixE/TlaeY-pzDGI/AAAAAAAAAuk/rU-Y8Q5HKYU/C%2525C3%2525B3pia%252520de%252520C%2525C3%2525B3pia%252520de%252520DSC00662.JPG"},
        {href: "#", code: "M 05.01", title: "<p>Casa com 3 dormit&oacute;rios, Sala, Cozinha, &aacute;rea de servi&ccedil;o, churrasqueira, p&aacute;tio e garagem.</p>", src: "https://lh3.googleusercontent.com/-CN4qz5FcWgM/UHRsHMQi0lI/AAAAAAAACws/saKGYvF6Iww/s576/FRENTE.jpg"},
        {href: "#", code: "M 03.03", title: "<p>Apartamento com 1 dormit&oacute;rio, sala, cozinha, banheiro e &aacute;rea de servi&ccedil;o.</p>", src: "https://lh5.googleusercontent.com/--7HPNpJ7z3Y/TyWr5nahUwI/AAAAAAAABww/Mw_ZZ62uo2o/s576/DSC01755.JPG"},
        {href: "#", code: "J 01.01", title: "<p>Apartamento de 70mt&sup2;, com 2 dormit&oacute;rios, todo com cer&acirc;mica, sal&atilde;o de festas, sala, cozinha, &aacute;rea de servi&ccedil;o. Aceita financiamento.</p>", src: "https://lh5.googleusercontent.com/-s6mRdzkvauI/T4x8fb4fLjI/AAAAAAAAB8A/6ZG44d1lg6s/s576/DSC01579.JPG"},
        {href: "#", code: "S 05.03", title: "<p>SALA COMERCIAl 46m&sup2; com 1 banheiro. CASA com sala, 2 quartos, banheiro, cozinha, p&aacute;tio, garagem e port&atilde;o. APARTAMENTO com sala, 2 quartos, banheiro, cozinha, dispensa de mantimentos, garagem coberta, muro e port&atilde;o. DEP&Oacute;SITO em baixo do apartamento.</p>", src: "https://lh4.googleusercontent.com/-YxEsjxjtWvk/ThNyRDBwv6I/AAAAAAAAATU/_Ma3vWCypeA/Destaque%252520externa%252520Casa%252520Itaparica.JPG"},
        {href: "#", code: "L 01.01", title: "<p>Casa com 3 dormit&oacute;rios, sala, cozinha, banheiro e &aacute;rea de servi&ccedil;o.</p>",  src: "https://lh5.googleusercontent.com/-rdBbfgX-_o8/T2dzpgmPd1I/AAAAAAAAB0g/vpgtEFErZbM/s576/DSC02313.JPG"},
        {href: "#", code: "V 01.02", title: "<p>Loja comercial com 29,76m&sup2; e 1 banheiro.</p>", src: "https://lh6.googleusercontent.com/-84s6ge4tj0U/TqhYQR4YweI/AAAAAAAABI4/bPh0IHjJ4-k/s576/C%2525C3%2525B3pia%252520de%252520DSC00390.JPG"},
        {href: "#", code: "A 03.01", title: "<p>Casa com 3 dormit&oacute;rios, sala de estar, sala de televis&atilde;o, cozinha, 2 banheiros, &aacute;rea de servi&ccedil;o, garagem, churrasqueira e p&aacute;tio grande.</p>", src: "https://lh6.googleusercontent.com/-30g9UU5Cgxo/Ti2vvCoAjpI/AAAAAAAAAag/PwB2s1nGB8s/2.JPG"},
        {href: "#", code: "I 05.01", title: "<p>2 casas no mesmo terreno + 1 sal&atilde;o nos fundos. Casa da frente com 2 dormit&oacute;rios, sala, banheiro e cozinha. A segunda casa possui 2 dormit&oacute;rios, sala e banheiro. O sal&atilde;o dos fundos possui duas salas pequenas e um sal&atilde;o grande.</p>", src: "https://lh4.googleusercontent.com/--xTE3wFOHTY/ToSzy3KchpI/AAAAAAAAA7U/XU1YF7gS2S0/Iara.jpg"},
        {href: "#", code: "J 01.01", title: "<p>Apartamento com 2 dormit&oacute;rios, 74,92 m&sup2;, sala, cozinha, banheiro c/ banheira e &aacute;rea de servi&ccedil;o, sacada ampla, no centro de Canoas.</p>", src: "https://lh3.googleusercontent.com/-BmD5zxMHKwY/UKPsgLOn4OI/AAAAAAAADBM/RQbgqQO3GRU/s576/DSC01900.JPG"},
        {href: "#", code: "P 03.07", title: "<p>JK N&deg;.104 Quarto e sala, banheiro, cozinha.</p>", src: "https://lh4.googleusercontent.com/-K4nxXskmlrY/T5b0n69KykI/AAAAAAAACOQ/fchuyA1G-us/s576/Demonstra%25C3%25A7%25C3%25A3o%2520Fachada%25201.jpg"},
        {href: "#", code: "M 14.01", title: "<p>Apartamento com 1 dormit&oacute;rio, sala, banheiro, cozinha e &aacute;rea de servi&ccedil;o.</p><p>&nbsp;</p>", src: "https://lh4.googleusercontent.com/--esh-AoQc-8/UI7LIvTDTRI/AAAAAAAAC4M/NoAD8UwJCn8/s576/DSC00487.JPG"},
        {href: "#", code: "J 03.03", title: "<p>LOJA com 1 banheiro.</p>", src: "https://lh3.googleusercontent.com/-AM3X4hCV798/ThMnp0MMlXI/AAAAAAAAALE/w1XBvO1O08o/Destaque%2525201052.JPG"},
        {href: "#", code: "J 03.04", title: "<p>LOJA com 1 banheiro.</p>", src: "https://lh5.googleusercontent.com/-5XzxdH2ugcE/ThMlRbhcW1I/AAAAAAAAAU4/xXPG6Axva5E/Destaque%2525201058.JPG"},
        {href: "#", code: "F00", title: "<p>Terreno de esquina, com 1500m&sup2;, alto e plano, excelente localiza&ccedil;&atilde;o. &Oacute;timo investimento.</p>", src: "https://lh5.googleusercontent.com/-MeX0yBHeqog/UgEImi-1dlI/AAAAAAAAEzU/1aQKd-N7TIo/s640/Flor%25C3%25AAncia%2520google.jpg"},
        {href: "#", code: "O01.16", title: "<p>Um pavilh&atilde;o comercial com 700m&sup2; e 5 banheiros.</p>", src: "https://lh4.googleusercontent.com/-4orhZ253PJo/UfZ7-wpCNmI/AAAAAAAAEGg/ixU7Rv166IA/s576/DSC06961.JPG"},
        {href: "#", code: "R 01.01", title: "<p>Apartamento com 2 dormit&oacute;rios, sala, cozinha e &aacute;rea de servi&ccedil;o, banheiro e garagem.</p>", src: "https://lh5.googleusercontent.com/-Fm_1wLWFjdY/UHMYy8MWXKI/AAAAAAAACr4/Q_Vrsap2DUM/s576/DSC03508.JPG"},
        {href: "#", code: "M 02.01", title: "<p>Apartamento JK, com 1 banheiro. Sala e quarto integrados e cozinha.</p>", src: "https://lh5.googleusercontent.com/-dy60-ctCcFA/UZKfIKu-e_I/AAAAAAAAD0s/y6np5c1lEfg/s576/DSC06297.JPG"},
        {href: "#", code: "F 02.01", title: "<p>Uma sala comercial com 2 banheiros, e uma cozinha. Metragem 6,50x13,60</p>", src: "https://lh5.googleusercontent.com/-a6ssK8iVd_o/VRmtQFv3FNI/AAAAAAAAIIc/hXtWn1XMkY4/s400/Destaque%2520Fachada.JPG"},
        {href: "#", code: "E 01.01", title: "<p>Apartamento com 1 dormit&oacute;rio, Sala, Cozinha, &Aacute;rea de servi&ccedil;o e Banheiro.</p>", src: "https://lh6.googleusercontent.com/-eV15lU1o0B8/ULecdeRNEfI/AAAAAAAADDw/wyXoIw96gJ0/s576/DSC04615.JPG"},
        {href: "#", code: "A 02.01", title: "<p>Casa com 2 dormit&oacute;rios, sala, cozinha, banheiro e p&aacute;tio grande.</p>", src: "https://lh6.googleusercontent.com/-rw3HZ5lTS2Y/T2d4pfnFiUI/AAAAAAAAB1Y/q6Lk3qaR-1I/s576/DSC02253.JPG"},
        {href: "#", code: "A 15", title: "<p>Loja comercial com Dep&oacute;sito, com 1 banheiro.&nbsp;Op&ccedil;&atilde;o com garagem= 3.000,00 reais.</p>", src: "https://lh6.googleusercontent.com/-cb6NhN8hRcg/Tih53VhYX6I/AAAAAAAAAmw/Ri6lB4fToJo/C%2525C3%2525B3pia%252520de%252520C%2525C3%2525B3pia%252520de%252520DSC00378.JPG"},
        {href: "#", code: "A 06.01", title: "<p>2 Casas no mesmo terreno. A casa da frente possui 2 quartos, sala, cozinha, banheiro, &aacute;rea de servi&ccedil;o e churrasqueira. A casa dos fundos possui 1 quarto, sala, cozinha, banheiro e &aacute;rea de servi&ccedil;o.</p>", src: "https://lh3.googleusercontent.com/-daDL348qh4I/Ti3Q9GZ55DI/AAAAAAAAAb0/_Lj5dqwIB8o/1.JPG"},
        {href: "#", code: "I 06.01", title: "<p>Casa com 3 dormit&oacute;rios, sala cozinha, sala de jantar, banheiro, lavabo, &aacute;rea de servi&ccedil;o, garagem e p&aacute;tio.</p>", src: "https://lh5.googleusercontent.com/-7guaHE3qjf8/Tp8rbASFubI/AAAAAAAABHI/iWZTH1Z2duQ/s576/DSC00979.JPG"},
        {href: "#", code: "V 01.03", title: "<p>Loja Comercial com 34,05m&sup2; e 1 banheiro.</p>", src: "https://lh6.googleusercontent.com/-84s6ge4tj0U/TqhYQR4YweI/AAAAAAAABI4/bPh0IHjJ4-k/s576/C%2525C3%2525B3pia%252520de%252520DSC00390.JPG"},
        {href: "#", code: "E 08.01", title: "<p>Apartamento t&eacute;rreo com 3 dormit&oacute;rios, 2 banheiros, Sala Ampla, cozinha, &aacute;rea de servi&ccedil;o, espa&ccedil;o gourmet e dois p&aacute;tios.</p><p>Apartamento Semi-mobiliado.</p>", src: "https://lh6.googleusercontent.com/-ekSVRvksEjo/Ti8k9OLW62I/AAAAAAAAAi0/0X69Ru1FpLA/C%2525C3%2525B3pia%252520%2525282%252529%252520de%252520DSC00479.JPG"},
        {href: "#", code: "A 15.05", title: "<p>Apartamento n&deg; 203, 2 dormit&oacute;rios, sala, cozinha, banheiro e &aacute;rea de servi&ccedil;o, e vaga para box coberto.</p>", src: "https://lh5.googleusercontent.com/-7SlcruTBHOQ/VWYVWs3yATI/AAAAAAAAIdg/JdCPcV-jlZw/w576-h300-no/Destaque.JPG"},
        {href: "#", code: "P 01.08", title: "<p>Apartamento 2 dormit&oacute;rios, sala, cozinha e banheiro.</p>", src: "https://lh4.googleusercontent.com/-K4nxXskmlrY/T5b0n69KykI/AAAAAAAACOQ/fchuyA1G-us/s576/Demonstra%25C3%25A7%25C3%25A3o%2520Fachada%25201.jpg"},
        {href: "#", code: "A 04.01", title: "<p>Apartamento com 3 dormit&oacute;rios, 3 salas, cozinha, &aacute;rea de servi&ccedil;o, banheiro e lavabo.</p>", src: "https://lh3.googleusercontent.com/-Y22i3UnGy6M/UJK7jEpYhKI/AAAAAAAAC6w/P0TGXAnE3nE/s576/DSC04068.JPG"},
        {href: "#", code: "J 04.01", title: "<p>Apartamento em condom&iacute;nio fechado com 2 dormit&oacute;rios, sala, cozinha, &aacute;rea de servi&ccedil;o e box coberto para 1 carro. Vai deixar o ar-condicionado (Split). O apartamento t&ecirc;m &oacute;tima solariza&ccedil;&atilde;o, com sol nos quartos, na sala e na &aacute;rea de servi&ccedil;o. O condom&iacute;nio possui &aacute;rea de lazer, sal&atilde;o de festas, piscina infantil e piscina adulta, quadra de esportes e churrasqueira com mesa e cadeiras.</p>", src: "https://lh4.googleusercontent.com/-GtrwRCRPGLE/T48eofaDy7I/AAAAAAAACEI/oxN2eawBqaw/s576/DSC00487.JPG"},
        {href: "#", code: "I 04.03", title: "<p>Sala comercial de 16m&sup2;, dentro de um centro de est&eacute;tica.</p>", src: "https://lh5.googleusercontent.com/-4ByfYFFpAoM/UP2LSNKTg0I/AAAAAAAADPY/xI41xjN34lc/s576/DSC05025.JPG"},
        {href: "#", code: "L 05.02", title: "<p>Casa com 2 dormit&oacute;rios, Cozinha, Banheiro, &aacute;rea de servi&ccedil;o, p&aacute;tio e garagem.</p>", src: "https://lh5.googleusercontent.com/-VdgeSk1iVsY/ThYAvUJpiQI/AAAAAAAAAQo/mfmn42rB5Hg/DSC00081.JPG"},
        {href: "#", code: "R 02.01", title: "<p>Apartamento com 3 dormit&oacute;rios, sala, cozinha, Sala de Jantar, banheiro e &aacute;rea de servi&ccedil;o com churrasqueira.</p>", src: "https://lh4.googleusercontent.com/-yqlO8T-OZmE/TpSLQhJxXeI/AAAAAAAAA9c/VBJQWxRTbW8/s576/DSC00491.JPG"},
        {href: "#", code: "L 03.01", title: "<p>Apartamento em Condom&iacute;nio fechado portaria 24 horas, &nbsp;com 2 dormit&oacute;rios, sala, cozinha, banheiro, &aacute;rea de servi&ccedil;o e vaga pra um carro.</p>", src: "https://lh3.googleusercontent.com/-yZ6O6aVWPxw/Uw4drGrvNcI/AAAAAAAAG8A/GJpDCq9bbLE/w640-h480-no/DSC08146.JPG"},
        {href: "#", code: "T 01.01", title: "<p>Casa em condom&iacute;nio fechado com 3 dormit&oacute;rios, sala, banheiro, cozinha, &aacute;rea de servi&ccedil;o, p&aacute;tio e garagem.</p>", src: "https://lh4.googleusercontent.com/-xKeeMhlNJJQ/T7v2o20pD5I/AAAAAAAACX0/LBtTpxmYhAQ/s576/DSC00209.JPG"},
        {href: "#", code: "G 01.01", title: "<p>Sala n&deg;. 403 Fundos, com 41,96 m&sup2; e um banheiro.</p>", src: "https://lh3.googleusercontent.com/-Gwuvdf2Mfnw/UP7PJW-PxNI/AAAAAAAADUc/0ybY8fjHQ1k/s640/DSC02507.JPG"},
        {href: "#", code: "P 01.06", title: "<p>Apartamento com 1 dormit&oacute;rio, sala, banheiro, cozinha e &aacute;rea de servi&ccedil;o.</p>", src: "https://lh4.googleusercontent.com/-K4nxXskmlrY/T5b0n69KykI/AAAAAAAACOQ/fchuyA1G-us/s576/Demonstra%25C3%25A7%25C3%25A3o%2520Fachada%25201.jpg"},
        {href: "#", code: "P 01.04", title: "<p>Apartamento com 1 dormit&oacute;rio, sala, banheiro, cozinha e &aacute;rea de servi&ccedil;o.</p>", src: "https://lh4.googleusercontent.com/-K4nxXskmlrY/T5b0n69KykI/AAAAAAAACOQ/fchuyA1G-us/s576/Demonstra%25C3%25A7%25C3%25A3o%2520Fachada%25201.jpg"},
        {href: "#", code: "P 01.02", title: "<p>Apartamento com 2 dormit&oacute;rios, sala, cozinha, banheiro e &aacute;rea de servi&ccedil;o.</p>", src: "https://lh6.googleusercontent.com/-roueXkD-kLE/T5b1Mga5OzI/AAAAAAAACOc/ccebje-A7js/s576/Demonstra%25C3%25A7%25C3%25A3o%2520Fachada%25202.jpg"},
        {href: "#", code: "P 00.01", title: "<p>Uma sala Comercial com 2 banheiros um ral de entrada e uma cozinha com arm&aacute;rio.</p>", src: "https://lh5.googleusercontent.com/-Ea0XEWHNr4c/U-uYzeDjpaI/AAAAAAAAHl4/PpQFflkXUPE/w640-h480-no/Foto%2BFachada%2Bdemostra%C3%A7%C3%A3o.JPG"},
        {href: "#", code: "P 01.05", title: "<p>Apartamento com 1 dormit&oacute;rio, sala, banheiro, cozinha e &aacute;rea de servi&ccedil;o.</p>", src: "https://lh4.googleusercontent.com/-K4nxXskmlrY/T5b0n69KykI/AAAAAAAACOQ/fchuyA1G-us/s576/Demonstra%25C3%25A7%25C3%25A3o%2520Fachada%25201.jpg"},
        {href: "#", code: "V 01",  title: "<p>Loja Comercial com 36,52m&sup2; e 1 banheiro.</p>", src: "https://lh4.googleusercontent.com/-As7G-INLFEw/Ti7KtHedO-I/AAAAAAAAAnY/nm0INAT9Eiw/s576/C%2525C3%2525B3pia%252520%2525282%252529%252520de%2525204.JPG"},
        {href: "#", code: "O 01.02", title: "<p>Casa com&nbsp;1 dorm,sala Cozinha ,Banheiro e &aacute;rea de servi&ccedil;o .</p>", src: "https://lh6.googleusercontent.com/-ywVm-pL0svw/ThNRk4n3fWI/AAAAAAAAAVA/qYrGqM-9fpU/Destaque%252520Dom%252520Pedro-%252520111.JPG"},
        {href: "#", code: "P 01.07", title: "<p>Apartamento JK, n&deg;.401, &nbsp;dormit&oacute;rio e sala integrada, cozinha e banheiro.</p>", src: "https://lh4.googleusercontent.com/-K4nxXskmlrY/T5b0n69KykI/AAAAAAAACOQ/fchuyA1G-us/s576/Demonstra%25C3%25A7%25C3%25A3o%2520Fachada%25201.jpg"},
        {href: "#", code: "E 02.01", title: "<p>Casa com 3 dormit&oacute;rios, 2 salas, 1 banheiro, cozinha, &aacute;rea de servi&ccedil;o, garagem coberta e p&aacute;tio com piscina. + 1 sala comercial. + 2 casas individuais, separada do terreno.</p>", src: "https://lh6.googleusercontent.com/-JTJ8RF1dF8Q/Tr1kcOPY_8I/AAAAAAAABXo/cUIMiG9AeoU/s576/DSC01082.JPG"},
        {href: "#", code: "S 08.01", title: "<p>Casa com 2 dormit&oacute;rios, Sala ampla, cozinha, banheiro, &aacute;rea de servi&ccedil;o e p&aacute;tio amplo.</p>", src: "https://lh3.googleusercontent.com/-2TU9q2W6-dg/UP2ZMtmTTdI/AAAAAAAADSk/nT066NyK5XQ/s576/DSC05090.JPG"},
        {href: "#", code: "L 06.01", title: "<p>Apartamento com 2 dormit&oacute;rios, sala, cozinha, banheiro e &aacute;rea de servi&ccedil;o.</p><p>op&ccedil;&atilde;o de Box: com Box R$ 770,00 e sem Box R$ 660,00</p>", src: "https://lh4.googleusercontent.com/-IMBAE68v7iE/UcySZyx82zI/AAAAAAAAD4Y/dwP3oudbTSc/s576/DSC03165.JPG"},
        {href: "#", code: "F 03.01", title: "<p>Apartamento com 2 dormit&oacute;rios, Sala, Cozinha, banheiro e &aacute;rea de servi&ccedil;o.</p>", src: "https://lh5.googleusercontent.com/-6SFyL_prpJw/UHSLcr_ygOI/AAAAAAAACzU/C7X5OfAPV9E/s576/DSC03720.JPG"},
        {href: "#", code: "GI030", title: "<p>Casa com 02 dormit&oacute;rios, (MAIOR BARBADA), em estado de nova, mais anexo com duas pe&ccedil;as, p&aacute;tio privativo. Terreno com gredes novas na frente.</p><p>Estuda proposta.</p><p>Aceita financiamento pela CAIXA.</p>", src: "https://lh3.googleusercontent.com/-TYher-GVadY/UnE3U6ZaP6I/AAAAAAAAGd0/AVH3LJNDFLo/s640/640-1.JPG"},
        {href: "#", code: "G 01.04", title: "<p>Sala de com &nbsp;41,96m&sup2; &nbsp;Fundos, com 1 banheiro.&nbsp;</p>", src: "https://lh6.googleusercontent.com/-aejR4kawSFY/UP7kNvUtG9I/AAAAAAAADVs/vk_ZUf_GxbA/s576/DSC02508.JPG"},
        {href: "#", code: "G 01.03", title: "<p>Sala comercial de 46,96m&sup2; com 1 banheiro. Frente.</p>", src: "https://lh3.googleusercontent.com/-Gwuvdf2Mfnw/UP7PJW-PxNI/AAAAAAAADUc/0ybY8fjHQ1k/s640/DSC02507.JPG"},
        {href: "#", code: "P 03.08", title: "<p>2 Dormit&oacute;rios, Sala, Cozinha, 1 Banheiro. N&atilde;o tem vaga para box.</p>", src: "https://lh3.googleusercontent.com/-A9dciWuAsdwbZDap4a3j7M3gdGJDQtNC74SrAtm5S0=w576-h300-no"},
        {href: "#", code: "GI032", title: "<p>&nbsp;Distrito Industrial de Cachoeirinha terreno (11 X 40 ), rua asfaltada de grande fluxo, &oacute;tima localiza&ccedil;&atilde;o, viabilidade comercial / industrial, acesso f&aacute;cil a principais saidas da cidade.</p><p>Estuda proposta.</p>", src: "https://lh4.googleusercontent.com/-f1O2dqCNGck/UlWzDyBbZDI/AAAAAAAAF7Y/hMFqGWj-Mf0/s640/640-1.jpg"},
        {href: "#", code: "S 02.04", title: "<p>Apartamento 1&deg; andar, &nbsp;com 3 dormit&oacute;rios, sala, cozinha, banheiro e &aacute;rea de servi&ccedil;o.</p>", src: "https://lh4.googleusercontent.com/-0TBKImMdlVc/U8PjthSCj1I/AAAAAAAAHXI/EQmcN2E9MFY/s640/Demostra%25C3%25A7%25C3%25A3o.JPG"},
        {href: "#", code: "J 02.07", title: "<p>Apartamento n&deg;. 201 fundos, com 2 dormit&oacute;rios, sala, cozinha, banheiro, &nbsp;&aacute;rea de servi&ccedil;o e garagem coberta.</p>", src: "https://lh6.googleusercontent.com/-D6-SY5WnnGI/US-uGlY892I/AAAAAAAADi8/IpNBNB7Emj0/s576/DSC05613.JPG"},
        {href: "#", code: "A 14", title: "<p>Apartamento com sala e quarto integrado, cozinha, banheiro e &aacute;rea de servi&ccedil;o.</p>", src: "https://lh3.googleusercontent.com/-p8CC7al5WJ8/Uh5cPSnXEZI/AAAAAAAAFSw/LeIIhcSmVSQ/s400/DSC07191.JPG"},
        {href: "#", code: "L 07.01", title: "<p>Casa com 3 dormit&oacute;rios, sala e cozinha integradas, banheiro, p&aacute;tio grande e &aacute;rea.&nbsp;</p>", src: "https://lh5.googleusercontent.com/-9n0ZL0_i480/UWMRxfvwhnI/AAAAAAAADkw/ZGE7VdmK_7c/s576/DSC06000.JPG"},
        {href: "#", code: "O 01.06", title: "<p>Casa em condom&iacute;nio com 1 dormit&oacute;rio, sala, cozinha, banheiro e &aacute;rea de servi&ccedil;o.</p>", src: "https://lh6.googleusercontent.com/-ywVm-pL0svw/ThNRk4n3fWI/AAAAAAAAAVA/qYrGqM-9fpU/s576/Destaque%2520Dom%2520Pedro-%2520111.JPG"},
        {href: "#", code: "J 02.09", title: "<p>Apartamento n&deg;. 203, &nbsp;com 2 dormit&oacute;rios, sala, cozinha, banheiro, &aacute;rea de servi&ccedil;o e garagem coberta.</p>", src: "https://lh6.googleusercontent.com/-D6-SY5WnnGI/US-uGlY892I/AAAAAAAADi8/IpNBNB7Emj0/w576-h300/DSC05613.JPG"},
        {href: "#", code: "P 01.01", title: "<p>Apartamento com 2 dormit&oacute;rios, sala, cozinha, banheiro e &aacute;rea de servi&ccedil;o.</p>", src: "https://lh6.googleusercontent.com/-roueXkD-kLE/T5b1Mga5OzI/AAAAAAAACOc/ccebje-A7js/s576/Demonstra%25C3%25A7%25C3%25A3o%2520Fachada%25202.jpg"},
        {href: "#", code: "GI029", title: "<p>Casa nova com 02 dormit&oacute;rios, box de estacionamento, em condom&iacute;nio fechado com playground, sal&atilde;o de festas, portaria, &oacute;tima oportunidade.</p>", src: "https://lh3.googleusercontent.com/-p4WeFZunk0s/UlRc655D1qI/AAAAAAAAF6E/HqvFwwxP3Pk/s640/6401.jpg"},
        {href: "#", code: "J 13.02", title: "<p>Apartamento- Frente, &nbsp;com 1 dormit&oacute;rio, sala, cozinha, &aacute;rea de servi&ccedil;o e sacada.</p>", src: "https://lh5.googleusercontent.com/-IAThsoEHks4/TyWrn6a4trI/AAAAAAAABwo/IBGfCJl8ChM/s640/DSC01755.JPG"},
        {href: "#", code: "GI034", title: "<p>&nbsp;Casa com &oacute;timo acabamento em esquina &agrave; 150 metros do Shopping do Vale em Cachoeirinha, 03 dormit&oacute;rios sendo uma su&iacute;te com banheira, cozinha com churrasqueira, 4 banheiros, garagem para 02 carros, terreno com grades.Excelente ponto comercial.</p><p>Aceita financiamento.</p><p>Estuda proposta.</p><p>51-8552 6448 oi 9903 6802 vivo 9322 9559 claro</p>", src: "https://lh3.googleusercontent.com/-FVSAIJFb0hU/UmAVszwD9bI/AAAAAAAAGRQ/ogzuTg2dHkU/s640/640-1.JPG"},
        {href: "#", code: "S 07.01", title: "<p>Apartamento semi- imobiliado de 1 dormit&oacute;rio, sala, cozinha, banheiro e &aacute;rea de servi&ccedil;o e garagem pra um carro.</p>", src: "https://lh4.googleusercontent.com/--esh-AoQc-8/UI7LIvTDTRI/AAAAAAAAC4M/NoAD8UwJCn8/s576/DSC00487.JPG"},
        {href: "#", code: "M.0.0", title: "<p>Casa&nbsp; com dois piso,&nbsp; 02 dormit&oacute;rios sendo um com su&iacute;te, sala, cozinha, banheiro e &aacute;rea de servi&ccedil;o, vaga pra carro.</p><p>&nbsp;</p><p>&nbsp;</p>", src: "https://lh4.googleusercontent.com/-3wdps9vAOgY/UqIHzvvPEYI/AAAAAAAAGlM/vvhiNVnHSyo/s640/DSC07586.JPG"},
        {href: "#", code: "P 02.01", title: "<p>Loja comercial &nbsp;de 45 m&sup2; com mezanino e 1 banheiro.</p>", src: "https://lh4.googleusercontent.com/-8vFGkz3iQM4/UiCKjSMS71I/AAAAAAAAFb4/WHUA-53gScM/s640/DSC01558.JPG"},
        {href: "#", code: "J 02.08", title: "<p>Apartamento n&deg;. 402, Fundos com 2 dormit&oacute;rios, sala, cozinha, banheiro, ar&eacute;a de servi&ccedil;o e garagem coberta.</p>", src: "https://lh6.googleusercontent.com/-D6-SY5WnnGI/US-uGlY892I/AAAAAAAADi8/IpNBNB7Emj0/w576-h300/DSC05613.JPG"},
        {href: "#", code: "GI005", title: "<p>Barbada. Pr&eacute;dio comercial com apartamento. Pr&eacute;dio com 220m&sup2;, &nbsp;3 quartos com banheiro (ou salas comerciais) mais duas salas com mesanino, &aacute;rea de servi&ccedil;o, garagem para 6 carros. Fundos com pr&eacute;dio comercial com 70 m&sup2;, 3 metros de altura, 2 banheiro e &aacute;rea de servi&ccedil;o, apartamento com 3 dormit&oacute;rios, cozinha americana, banheiro, &nbsp;&aacute;rea de servi&ccedil;o e sacada. Tudo isso &aacute; poucos metros da centro de Canoas, pr&oacute;ximo ao Forum. Aceita permuta. Estudamos a &nbsp;proposta.&nbsp;</p>", src: "https://lh5.googleusercontent.com/-zbxpgfL8Kgk/UfwJP6j5CjI/AAAAAAAAEj0/CChi5whSxdE/s640/DSC06452.JPG"},
        {href: "#", code: "J 02.11", title: "<p>Pavilh&atilde;o comercial com 750m&sup2;, sendo que tem um mezanino e banheiro.</p>", src: "https://lh3.googleusercontent.com/-yApffL1kHXg/UYAEzK8AmqI/AAAAAAAADr4/Q9Be8O0xyOU/w576-h300/photo.jpg"},
        {href: "#", code: "GI010", title: "<p>Terrenos escriturados, altos e planos, 500m&sup2; cada, em regi&atilde;o em grande desenvolvimento. Vendo um por R$148.000,00 ou estudo proposta em mais de um, &aacute;rea total 1500 m&sup2; (30X50).Exlente Investimento.</p>", src: "https://lh6.googleusercontent.com/-Owlb-lg5ZpQ/UgjlwAWZiPI/AAAAAAAAE-0/-TioAqhXa50/s640/4-painel-destaque-DSC05541.JPG"},
        {href: "#", code: "GI011", title: "<p>Terreno (12X50), de esquina, pr&oacute;ximo de ponto de &ocirc;nibus, escolas e comercio variado.</p><p>Excelente investimento.</p>", src: "https://lh5.googleusercontent.com/-PhLfgeKrY6E/UgkdKAcz-kI/AAAAAAAAFAg/-Ihi1y2_8os/s640/DSC05851.JPG"},
        {href: "#", code: "J 06.01", title: "<p>Casa de dois pisos com 2 su&iacute;tes, banheiro social, sala, cozinha, espa&ccedil;o com bancada americana na cozinha, escrit&oacute;rio, &aacute;rea de lazer com piscina, garagem, p&aacute;tio e 3&ordm; piso para construir mais andares.</p>", src: "https://lh5.googleusercontent.com/-zND32w4yj9I/TxcVoZAA02I/AAAAAAAABnU/daWrBSrjt10/s576/DSC01373.JPG"},
        {href: "#", code: "GI013", title: "<p>Casa de alvenaria com 70 m&sup2;, em um terreno de 12x38, alto e plano. Casa com 01 dormit&oacute;rio, com possibilidade de 02, sala ampla, cozinha, area de servi&ccedil;o, churrasqueira, por&atilde;o, adega, garagem, &oacute;tima localiza&ccedil;&atilde;o, ponto de &ocirc;nibus, com&eacute;rcio vari&aacute;do.</p><p>Financi&aacute;vel.</p><p>Estuda-se proposta.</p>", src: "https://lh5.googleusercontent.com/-0JvM5fnFrCg/UhSsF3aNfHI/AAAAAAAAFKs/PJsTbqgPTls/s640/DSC06618.JPG"},
        {href: "#", code: "F 02.01", title: "<p>Casa com 2 dormit&oacute;rios, banheiro, sala e cozinha integrada, &aacute;rea de servi&ccedil;o e p&aacute;tio grande. Terreno de 337,80 m&sup2;.</p>", src: "https://lh6.googleusercontent.com/-hmVUCcFnnH8/TxeNdKvWCJI/AAAAAAAABvU/B8E2IIUkcEs/s576/DSC01220.JPG"},
        {href: "#", code: "GI016", title: "<p>Terreno de esquina, 2500 m&sup2;, plano, em excelente localiza&ccedil;&atilde;o, ideal para condom&iacute;nio residencial, &oacute;timo ponto comercial.</p><p>PARA INVESTIDORES.</p>", src: "https://lh6.googleusercontent.com/-NTn09jtE0mU/Uh9_FsDse2I/AAAAAAAAFao/oUdWz3DpHJs/s640/Terreno%2520Alexandre%2520de%2520Gusm%25C3%25A3o%25202500m%25C2%25B2%2520Sr.%2520Rogerio.jpg"},
        {href: "#", code: "M 20.01", title: "<p>Casa com 3 dormit&oacute;rios, sendo 1 su&iacute;te, sala, banheiro, cozinha, &aacute;rea de servi&ccedil;o, p&aacute;tio, &aacute;rea de lazer com churrasqueira e garagem coberta para 1 carro, e descoberta para 4 carros.</p>", src: "https://lh4.googleusercontent.com/-pWOvIMK99mI/T5Bd_UAG3OI/AAAAAAAACJE/4RNbBjmPZgk/s576/DSC01573.JPG"},
        {href: "#", code: "GI043", title: "<p>Casa 02 dormit&oacute;rios, sala, cozinha, 01 banheiro, garagem, terreno 13 X 27 com grades, &oacute;tima localiza&ccedil;&atilde;o, &agrave; poucos metros da Av. Santos Ferreira. Terreno com escritura, casa N&Atilde;O averbada.</p><p>&nbsp;</p>", src: "https://lh4.googleusercontent.com/-2hHwTLXvDxw/Uw3ugPXmNyI/AAAAAAAAABw/Hqd-jo3XXIA/s640/DSC07646%2520640x480.jpg"},
        {href: "#", code: "P 03.04", title: "<p>Loja com aproximadamente 60m&sup2; e 1 banheiro.</p>", src: "https://lh6.googleusercontent.com/-roueXkD-kLE/T5b1Mga5OzI/AAAAAAAACOc/ccebje-A7js/s576/Demonstra%25C3%25A7%25C3%25A3o%2520Fachada%25202.jpg"},
        {href: "#", code: "A 13.03", title: "<p>Uma sala comercial com 200m&sup2;, 1 cozinha, 3 banheiros , churrasqueira e garagem para 2 carros.</p>", src: "https://lh4.googleusercontent.com/-M7gsXRMjHjo/U8VyGAmxwII/AAAAAAAAHYs/AhTW0uZ8R34/w702-h454-no/001.JPG"},
        {href: "#", code: "GI014", title: "<p>Terreno no bairro Niter&oacute;i (11X44), com duas casas, uma de alvenaria e outra mista, excelente localiza&ccedil;&atilde;o, a poucos metros da BR-116.</p><p>&Oacute;timo investimento.</p>", src: "https://lh5.googleusercontent.com/-ScOR0Myc7yY/UhUBwsLBqSI/AAAAAAAAFNk/Ba7095J5T0g/s640/DSC06538.JPG"},
        {href: "#", code: "GIP001", title: "<p>Casa com 02 dormit&oacute;rios, sala, cozinha, &aacute;rea de servi&ccedil;o, garagem, p&aacute;tio na frente, quintal amplo, terreno alto em rua tranquila, com com&eacute;rcio variado.</p>", src: "https://lh4.googleusercontent.com/-QWGjp_BooRs/Ui3E7fQF59I/AAAAAAAAFvI/GOHANGgwi3E/s640/1.jpg"},
        {href: "#", code: "GI033", title: "<p>Sobrado melhor localiza&ccedil;&atilde;o Moinhos de Vento, pr&oacute;ximo &agrave; centro comercial e novo shopping, 3 dormit&oacute;rios sendo um suite com closet e sacada, ar condicionado split 12000 btus, escrit&oacute;rio, 2 dormit&oacute;rios de visitas, hall de entrada, sala de estar, sala de jantar, cozinha, lavabo, w.c social, lavanderia, garagem coberta dois carros, e mais dois carros descobertos, quiosque com fog&atilde;o campeiro, churrasqueira, wc social, lavanderia, patio com espera para piscina, espera para &aacute;gua quente, junquer, todo murado, com grades e port&atilde;o eletr&ocirc;nico.Im&oacute;vel com apenas um ano de constru&ccedil;&atilde;o, aceita financiamento, estuda proposta. Aceita outro im&oacute;vel de menor valor.<br />51-8552 6448 oi 9903 6802 vivo 93229559 claro</p>", src: "https://lh4.googleusercontent.com/-IvuP-9mHY3E/UmArPXmOo_I/AAAAAAAAGWw/ufoaqjs2OvE/s400/640-1.jpg"},
        {href: "#", code: "M 16.01", title: "<p>Casa de 247,84m&sup2;, com 3 dormit&oacute;rios, sot&atilde;o com espa&ccedil;o de mais 1 quarto, cozinha, &aacute;rea de servi&ccedil;o, sala de estar e sala de jantar integradas, p&aacute;tio na parte de tr&aacute;s e p&aacute;tio lateral com entrada alternativa, estacionamento para 2 carros, condom&iacute;nio com espa&ccedil;o fitness, brinquedoteca, sala de jogos, quadra de esportes, piscina adulto, piscina infantil, quiosques para fazer churrasco, e 2 sal&otilde;es de festas.</p>", src: "https://lh6.googleusercontent.com/-ZpC3L5xOciI/USz9A2NORkI/AAAAAAAADcU/HP8-OgfJvsg/s576/DSC05834.JPG"},
        {href: "#", code: "GI026", title: "<p>Sobrado 04 dormit&oacute;rios, 02 banheiros, escrit&oacute;rio,sala de estar, cozinha, &aacute;rea de servi&ccedil;o, lavanderia, dep&oacute;sito, garagem para quatro carros com churrasqueira, p&aacute;tio amplo todo cal&ccedil;ado, &oacute;tima localiza&ccedil;&atilde;o.</p><p>Aceita financiamento.</p><p>Estuda proposta.</p>", src: "https://lh6.googleusercontent.com/-Wg2puooeE3I/Ulg6UJmB1AI/AAAAAAAAGE0/9EBdoi4Mk0c/s640/640-1.jpg"},
        {href: "#", code: "GI001", title: "<p>Apartamento 66 m&sup2;, andar t&eacute;rreo, 2 dorm&iacute;torios, sala, cozinha, banheiro, &aacute;rea de servi&ccedil;o, garagem ao lado do apartamento, p&aacute;tio privativo, acabamento em gesso, excelente localiza&ccedil;&atilde;o, pr&oacute;ximo do centro.</p>", src: "https://lh4.googleusercontent.com/-L3LjStHo89w/UfF65BNSwgI/AAAAAAAAEBk/XQuc9IKR2ds/s576/DSC06486.JPG"},
        {href: "#", code: "P 03.01", title: "<p>Apartamento n&deg;. 303, &nbsp;com &nbsp;2 dormit&oacute;rios, sala, cozinha, &nbsp;banheiro, &aacute;rea de servi&ccedil;o, churrasqueira, sacada e garagem coberta.</p>", src: "https://lh3.googleusercontent.com/-CzGe7nNALhs/UiD5QLfaryI/AAAAAAAAFmA/eflfjwKGy1U/s640/Foto%2520Fachada.JPG"},
        {href: "#", code: "M 05.16", title: "<p>Um &nbsp;terreno com a metragem &nbsp;10x230.</p><p>&nbsp;</p>", src: "https://lh5.googleusercontent.com/-Ri-9bZ5FSO0/U-DNAgMY9VI/AAAAAAAAHdM/jQuc2-uTCEA/w576-h300-no/Destaque.JPG"},
        {href: "#", code: "P 00", title: "<p>Terreno com 13,00 frente e 45,00 comprimento. &Aacute;rea total 585m&sup2;.</p>", src: "https://lh3.googleusercontent.com/-YT0SzUpsYUA/UZKVoCq4VfI/AAAAAAAADz8/datk0CrrwOo/s576/TERRENO%2520Rua%2520Manoel%2520Galbo.jpg"},
        {href: "#", code: "N. 01", title: "<p>Casa de 484 m&sup2;, 11 X 44. 3 dormit&oacute;rios, 3 banheiros, sala de estar, cozinha, &aacute;rea de servi&ccedil;o, p&aacute;tio grande, garagem + 1 loja comercial.</p>", src: "https://lh4.googleusercontent.com/-vzKL7L4UNtc/Tp8Y-dZDTbI/AAAAAAAABFo/ckwYALXIMmU/s576/DSC00926.JPG"},
        {href: "#", code: "M 04", title: "<p>Loja com 75m&sup2; e um banheiro,&nbsp;</p>", src: "https://lh3.googleusercontent.com/-cRelY-aCWno/UZUfxV0EBCI/AAAAAAAAD2M/bZhpPkdGaEY/s576/DSC06299.JPG"},
        {href: "#", code: "V 2", title: "<p>Apartamento com 119m&sup2;, 2 quartos sendo 1 su&iacute;te, 1 banheiro, sala de jantar, sala de estar, cozinha, &aacute;rea de servi&ccedil;o, &aacute;rea externa, sacada e garagem para 1 carro.</p>", src: "https://lh3.googleusercontent.com/-k9MpPAlHNTs/UOsN8WoJHkI/AAAAAAAADFw/C032CiJwgUQ/s576-Ic42/DSC03494.JPG"},
        {href: "#", code: "GI052", title: "<p>Apartamento novo com 02 dormit&oacute;rios, &aacute;rea de servi&ccedil;o, piso cer&acirc;mico, melhor posi&ccedil;&atilde;o solar, condom&iacute;nio com sal&atilde;o de festas, quadra poliesportiva, playground, portaria 24 hs, pr&oacute;ximo da esta&ccedil;&atilde;o Trensurb /F&aacute;tima e a 5 minutos do centro de Canoas.</p><p>AGENDE UMA VISITA.</p><p>51-8552 6448 oi 9903 6802 vivo 9386 8670 claro</p>", src: "https://lh3.googleusercontent.com/-RBw_BblHNLo/UyyPFlww4MI/AAAAAAAAADw/y9Q2jf4RPsA/s640/640x480.JPG"},
        {href: "#", code: "M 13.02", title: "<p>apartamento de 1 dormit&oacute;rio, sala, cozinha, banheiro e &aacute;rea de servi&ccedil;o sem vaga de box.</p>", src: "https://lh3.googleusercontent.com/-XX8_euMEh5w/UvTIpmjU5JI/AAAAAAAAG0c/zmZvaKWYV_4/s480/01.JPG"},
        {href: "#", code: "E 07.01", title: "<p>Residencial dos Alamos. Apartamento com 2 dormit&oacute;rios, semi-mobiliado, sala, cozinha, banheiro, &aacute;rea de servi&ccedil;o e estacionamento para 1 carro. Condom&iacute;nio possui sal&atilde;o de festas, 4 espa&ccedil;os com churrasqueira e pra&ccedil;a com brinquedos para crian&ccedil;as.</p>", src: "https://lh6.googleusercontent.com/-1fORhoEGATc/USZ5DFNnP0I/AAAAAAAADa8/vs9tU4ieUZk/s576/DSC05636.JPG"},
        {href: "#", code: "J 13.03", title: "<p>Apartamento com 1 dormit&oacute;rio, sala, cozinha e &aacute;rea de servi&ccedil;o.</p>", src: "https://lh6.googleusercontent.com/-IAThsoEHks4/TyWrn6a4trI/AAAAAAAABwo/IBGfCJl8ChM/w640-h480-no/DSC01755.JPG"},
        {href: "#", code: "P 02.02", title: "<p>Loja Comercial com 45 m&sup2; e um banheiro.</p>", src: "https://lh3.googleusercontent.com/-6pT2XWYv-SU/UiCK6v4mTRI/AAAAAAAAFcE/KuGKl0PSZuw/s576-Ic42/DSC01558.JPG"},
        {href: "#", code: "G I009", title: "<p>PAVILH&Atilde;O em &aacute;rea industrial com 320m (10X32) , p&eacute; direito 6,5 metros, mezanino, em terreno de 500 m&sup2; (10X50), piso industrial, escrit&oacute;rio, 02 banheiros, sistema de g&aacute;s industrial central, cerca el&eacute;trica, sistema de monitoramento, estrutura para 2&ordm; pavimento.</p><p>&nbsp;</p><p>N&Atilde;O FINANCIA POR BANCO.</p><p>ESTUDA PROPOSTA.</p>", src: "https://lh5.googleusercontent.com/-smOJLJsya80/UgKA3mzElrI/AAAAAAAAE6E/v4PjLCrE6U4/s640/DSC06101.JPG"},
        {href: "#", code: "S 02.05", title: "<p>Apartamento, com 3 dormit&oacute;rios, sala, cozinha, banheiro, &aacute;rea de servi&ccedil;o,varanda, sacada,&nbsp;&nbsp; e vaga para carro.</p>", src: "https://lh6.googleusercontent.com/-Tc-_aZf1Tuw/U-O_yM0YVdI/AAAAAAAAHkk/iEvyKjRbvdA/w357-h477-no/DSC09619.JPG"},
        {href: "#", code: "A 15.02", title: "<p>Apartamento n&deg; 103, 2 dormit&oacute;rios, Sala, Cozinha, Banheiro, &Aacute;rea de Servi&ccedil;o e Estacionamento Coberto.</p>", src: "https://lh5.googleusercontent.com/-OxHvL1jqXLY/VWYerBKy2wI/AAAAAAAAIko/SJGdhhESoxY/w576-h300-no/Destaque.JPG"},
        {href: "#", code: "A 15.01", title: "<p>Apartamento n&deg;.104, &nbsp;com 2 dormit&oacute;rios, sala, cozinha banheiro e &aacute;rea de servi&ccedil;o mais vaga de Box.</p>", src: "https://lh5.googleusercontent.com/-8IniFNyReWA/U7vmrIQNBRI/AAAAAAAAHRE/XPeaVbNy1q4/s620/Fachada%2520demostra%25C3%25A7%25C3%25A3o.JPG"},
        {href: "#", code: "J 02.12", title: "<p>Apartamento n&deg;. 403, &nbsp;Fundos com &nbsp;2 dormit&oacute;rios, sala, cozinha, banheiro, &aacute;rea de servi&ccedil;o e garagem coberta.</p>", src: "https://lh6.googleusercontent.com/-vmEO4MOTqmo/UffEPZe9kLI/AAAAAAAAEKI/8Fl0UG8YcHM/s576/DSC05564.JPG"},
        {href: "#", code: "M 05.17", title: "<p>Casa Mista sozinha no p&aacute;tio com 2 dormit&oacute;rios, sala, cozinha, banheiro, e &aacute;rea de serv&ccedil;o, garagem coberta para um carro e um amplo p&aacute;tio.</p>", src: "https://lh5.googleusercontent.com/-V6rk_C3yn-E/VVD6sEo06pI/AAAAAAAAIRY/IeculNFH4EQ/w576-h300-no/DSC00176.JPG"},
        {href: "#", code: "GI007", title: "<p>Lindo sobrado com 03 su&iacute;tes, um terreno de 12X27, &aacute;rea construida 180 m&sup2;,tudo registrado na prefeitura, s&oacute; falta pegar o habite-se, pois a casa foi ampliada.</p><p>Piso porcelanato Monalisa, balc&atilde;o da cozinha de granito S&atilde;o Gabriel, fog&atilde;o Kooptop embutido no granito, escadaria de granito travestido, com corrim&atilde;o de a&ccedil;o in&oacute;x escovado com laterais de vidro, sala com t&eacute;to de gesso com luzes de Led internas na sanca, 03 suites, 04 banheiros,02 sacadas na frente e 02 atr&aacute;s, caixa d&aacute;gua de 1000 litros, garagem para 02 carros, entrada para &aacute;gua quente &nbsp;para a pia da cozinha e chuveiros das su&iacute;tes.</p><p>Rua calma e tranquila, pr&oacute;ximo de escolas, &ocirc;nibus e com&eacute;rcio variado.</p><p>Aceita imovel de menor valor e autom&oacute;vel.</p><p>Im&oacute;vel financi&aacute;vel.</p><p>Estuda-se proposta.</p><p>&nbsp;</p>", src: "https://lh6.googleusercontent.com/-aGvs5LxkEa4/UgA4iE65yeI/AAAAAAAAEuU/kJbqvXPFDoE/s640/Frente.JPG"},
        {href: "#", code: "T 04.01", title: "<p>Apartamento com 1 Dormit&oacute;rio, Sala, Cozinha, Banheiro, &Aacute;rea de Servi&ccedil;o, Sem vaga para Box.</p>", src: "https://lh3.googleusercontent.com/t19dRuqp7qjWY5e20nzslHel_5ScVQo8fNNxeNz9vD8=w576-h300-no"},
        {href: "#", code: "M 05.18", title: "<p>Casa mista, 2 dormit&oacute;rios, Sala, Cozinha, Banheiro, Despensa, &nbsp;&Aacute;rea de Servi&ccedil;o, Vaga para carro, com amplo p&aacute;tio.</p>", src: "https://lh5.googleusercontent.com/-Nqb3_3e6Zi8/VWYoQ5MD_tI/AAAAAAAAIsk/6A0CIYSVDZ8/w576-h300-no/IMG_1388.jpg"},
        {href: "#", code: "A 04.03", title: "<p>1 dormit&oacute;rio, Sala, Cozinha, Banheiro. Sem vaga para box.</p>", src: "https://lh3.googleusercontent.com/LsJJ21vMFZeGFXkdRNWinB48uA9VFNiTLTFbVCCP6Fk=w225-h300-no"},
        {href: "#", code: "A 15.03", title: "<p>Apartamento n&deg;102 Frente, &nbsp;de 2 dormit&oacute;rio &nbsp;sendo que o de casal tem mobilia, sala, cozinha j&aacute; com arm&aacute;rios, banheiro, &aacute;rea de servi&ccedil;o e vaga pra Box coberto.</p>", src: "https://lh6.googleusercontent.com/-5c8e1dbs5No/VFd3fdAbcWI/AAAAAAAAH6g/-oqAfrOqxtg/w576-h300-no/Fachada.JPG"},
        {href: "casa_venda_001.html", code: "C001", title: "Casa de 01 de Dormitório em Canoas.", src: "img/foto_01_700x450.jpg"},
        {href: "casa_venda_001.html", code: "C001", title: "Casa de 01 de Dormitório em Canoas.", src: "img/foto_02_700x450.jpg"},
        {href: "casa_venda_001.html", code: "C001", title: "Casa de 01 de Dormitório em Canoas.", src: "img/foto_03_700x450.jpg"},
        {href: "casa_venda_001.html", code: "C001", title: "Casa de 01 de Dormitório em Canoas.", src: "img/foto_04_700x450.jpg"},
        {href: "casa_venda_001.html", code: "C001", title: "Casa de 01 de Dormitório em Canoas.", src: "img/foto_05_700x450.jpg"},
        {href: "casa_venda_001.html", code: "C001", title: "Casa de 01 de Dormitório em Canoas.", src: "img/foto_06_700x450.jpg"}
    ];

    //loadParametros();
    //loadBanners();
    //loadDestaques();

});
